@SpaceRouteService_HostAddress = http://localhost:5291

GET {{SpaceRouteService_HostAddress}}/weatherforecast/
Accept: application/json

GET {{SpaceRouteService_HostAddress}}/spaceport/findbyname
Accept: text/plain

###
